[mypy]
python_version = 3.13
ignore_missing_imports = True
# exclude venv and legacy references to avoid third-party linting
exclude = (^ref/)|(^\.venv/)|(.*/ref/legacy/)|(.*/ref/cli/)|(.*/ref/dashboard/)
strict = False
