# Auto-generated by MCPServer


def greet(name: str) -> str:
    """Return a greeting message."""
    return f"Hello, {name}!"


# Added by MCPServer: farewell helper
def farewell(name: str) -> str:
    """Return a farewell message."""
    return f"Goodbye, {name}!"


# Demonstration calls
if __name__ == "__main__":
    print(greet("World"))
    print(farewell("World"))
